version: '3.7'

services:
  # Servidor de Tracking MLflow
  mlflow-server:
    image: ghcr.io/mlflow/mlflow:v2.3.1
    container_name: tracker_mlflow
    ports:
      - "5000:5000"
    command: >
      mlflow server
      --backend-store-uri sqlite:///mlflow.db
      --default-artifact-root ./mlartifacts
      --host 0.0.0.0
    volumes:
      - ./mlflow_data:/mlflow

  # Interface UI (opcional, mas útil para visualização rápida)
  # Acessível em localhost:5000
